package com.nemless.school_wits.config;

public class ResponseMessage {
    public static final String ENROLLMENT_SUCCESSFUL = "Course enrollment successful";
    public static final String PAYMENT_APPROVAL_UPDATED = "Payment approval updated";
    public static final String EMAIL_EXISTS = "Another account with this email already exists";
    public static final String QUIZ_RESULT_EXISTS = "The student has already given this quiz";
    public static final String INCORRECT_CREDENTIALS = "Incorrect credentials";
    public static final String INVALID_TOKEN = "Token invalid or expired";
    public static final String INVALID_FILE = "File is invalid";
    public static final String INVALID_FILE_TYPE = "Please upload video or pdf";
    public static final String INVALID_USER_ID = "User id is invalid";
    public static final String INVALID_COURSE_ID = "Course id is invalid";
    public static final String INVALID_ENROLLED_COURSE_ID = "Enrolled course id is invalid";
    public static final String INVALID_COURSE_TOPIC_ID = "Topic id is invalid";
    public static final String INVALID_VIDEO_ID = "Video id is invalid";
    public static final String INVALID_QUIZ_ID = "Quiz id is invalid";
    public static final String INVALID_QUIZ_RESULT_ID = "Quiz result id is invalid";
    public static final String INVALID_QUESTION_ID = "Question id is invalid";
    public static final String INVALID_FILE_ID = "File id is invalid";
    public static final String ENROLLMENT_EXISTS = "Student is already enrolled in this course";
    public static final String UNABLE_TO_UPLOAD = "Can not upload file at this moment";
    public static final String UNABLE_TO_PERFORM_DATABASE_OPERATION = "Error while performing database operation";
    public static final String UNABLE_TO_DOWNLOAD = "Can not download file at this moment";
    public static final String UNABLE_TO_STREAM = "Can not stream file at this moment";
    public static final String UNABLE_TO_DELETE = "Can not delete file at this moment";
    public static final String INVALID_AMOUNT = "Amount is invalid";
    public static final String UNAUTHORIZED_RESOURCE_REQUEST = "Resource request is unauthorized";
    public static final String INVALID_QUESTION_ANSWER = "One or more question or answer id is invalid";
    public static final String NOTICE_POSTED = "Notice posted";
    public static final String INVALID_NOTICE_RECIPIENT = "There is no recipient for this notice";
    public static final String INVALID_COURSE_BUNDLE = "No course bundle available for this grade";
    public static final String COURSE_DELETE_SUCCESSFUL = "Course deletion successful";
    public static final String COURSE_TOPIC_DELETE_SUCCESSFUL = "Course topic deletion successful";
    public static final String COURSE_FILE_DELETE_SUCCESSFUL = "Course file deletion successful";
    public static final String QUIZ_DELETE_SUCCESSFUL = "Quiz deletion successful";
    public static final String QUIZ_QUESTION_DELETE_SUCCESSFUL = "Quiz question deletion successful";
    public static final String QUIZ_ANSWER_DELETE_SUCCESSFUL = "Quiz answer deletion successful";
    public static final String CORRECT_ANSWER_REQUIRED = "You have to provide the correct answer first";
    public static final String SEARCH_PARAMS_REQUIRED = "Provide parameters to search for users";
    public static final String PASSWORD_CHANGE_SUCCESSFUL = "Password changed successfully";
    public static final String CURRENT_PASSWORD_DOES_NOT_MATCH = "Current password does not match";
    public static final String PASSWORDS_DO_NOT_MATCH = "New passwords do not match";
}
