services:
  postgres:
    image: postgres:17
    container_name: postgresql
    environment:
      POSTGRES_DB: school-wits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-wits-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - /var/www/schoolwits/media/data:/app/data
      - /var/www/schoolwits/backend/logs:/app/logs
    networks:
      - backend
      - monitoring

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - /var/www/schoolwits/backend/logs:/app/logs
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=supersecuregrafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring

volumes:
  postgres_data:
  prometheus_data:
  grafana_storage:

networks:
  backend:
  monitoring:
