version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgresql
    environment:
      POSTGRES_DB: school-wits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-wits-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - /var/www/schoolwits/media/data:/app/data
      - /var/www/schoolwits/logs:/app/logs
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
