server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: school-wits
    static_configs:
      - targets:
          - localhost
        labels:
          job: school-wits
          __path__: /app/logs/**/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<level>[A-Z]+) .*'
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05"
      - labels:
          level: