server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  application:
    name: SchoolWits
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/school-wits
    username: postgres
    password: tiger
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  jwt:
    secret: 743d253555a5aaf68e3adf8faade4f5db388dc2958da14bcdd01ebaba8728ecc
    expiration: 30000000
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

upload-directory: /app/data/
api:
  server:
    url: https://backend.schoolwits.com