CREATE TABLE public.attendance (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date timestamp(6) without time zone NOT NULL,
    is_late boolean NOT NULL,
    is_present boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    enrolled_course_id bigint
);



ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.barchart_values (
    course_information_id bigint NOT NULL,
    topic_value integer,
    topic_name character varying(255) NOT NULL
);



CREATE TABLE public.contact_request (
    id bigint NOT NULL,
    contact character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    message character varying(255) NOT NULL,
    resolved boolean NOT NULL
);



ALTER TABLE public.contact_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.course (
    id bigint NOT NULL,
    academic_session character varying(255),
    course_image character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    discount_last_date timestamp(6) without time zone,
    discounted_fee real NOT NULL,
    fee real NOT NULL,
    grade character varying(255) NOT NULL,
    mode character varying(255) NOT NULL,
    number_of_exams integer NOT NULL,
    number_of_lessons integer NOT NULL,
    number_of_notes integer NOT NULL,
    number_of_quizzes integer NOT NULL,
    number_of_session integer NOT NULL,
    number_of_worksheet integer NOT NULL,
    session_duration character varying(255),
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    uid character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT course_grade_check CHECK (((grade)::text = ANY ((ARRAY['VI'::character varying, 'VII'::character varying, 'VIII'::character varying, 'IX'::character varying, 'X'::character varying])::text[]))),
    CONSTRAINT course_mode_check CHECK (((mode)::text = ANY ((ARRAY['IN_PERSON'::character varying, 'ONLINE'::character varying])::text[]))),
    CONSTRAINT course_type_check CHECK (((type)::text = ANY ((ARRAY['SHORT'::character varying, 'LONG'::character varying])::text[])))
);



CREATE TABLE public.course_bundle (
    id bigint NOT NULL,
    discounted_fee real NOT NULL,
    fee real NOT NULL,
    grade character varying(255) NOT NULL,
    mode character varying(255) NOT NULL,
    CONSTRAINT course_bundle_grade_check CHECK (((grade)::text = ANY ((ARRAY['VI'::character varying, 'VII'::character varying, 'VIII'::character varying, 'IX'::character varying, 'X'::character varying])::text[]))),
    CONSTRAINT course_bundle_mode_check CHECK (((mode)::text = ANY ((ARRAY['IN_PERSON'::character varying, 'ONLINE'::character varying])::text[])))
);



CREATE TABLE public.course_bundle_course (
    course_bundle_id bigint NOT NULL,
    course_id bigint NOT NULL
);



ALTER TABLE public.course_bundle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_bundle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.course_file (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    file_name character varying(255) NOT NULL,
    file_uid character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255),
    updated_at timestamp(6) without time zone,
    course_topic_id bigint NOT NULL,
    CONSTRAINT course_file_type_check CHECK (((type)::text = ANY ((ARRAY['VIDEO'::character varying, 'PDF'::character varying])::text[])))
);



ALTER TABLE public.course_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE public.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.course_information (
    id bigint NOT NULL,
    academic_plan oid NOT NULL,
    assessment oid NOT NULL,
    description oid NOT NULL,
    learning_content_list oid NOT NULL,
    learning_content_title oid NOT NULL,
    title character varying(255) NOT NULL,
    course_id bigint NOT NULL,
    core_learning_areas text
);



ALTER TABLE public.course_information ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_information_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.course_plan_information (
    id bigint NOT NULL,
    course_information_id bigint NOT NULL
);



ALTER TABLE public.course_plan_information ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_plan_information_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.course_plan_week_details_information (
    id bigint NOT NULL,
    text character varying(255) NOT NULL,
    course_plan_week_information_id bigint NOT NULL
);



ALTER TABLE public.course_plan_week_details_information ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_plan_week_details_information_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.course_plan_week_information (
    id bigint NOT NULL,
    text character varying(255) NOT NULL,
    course_plan_information_id bigint NOT NULL
);



ALTER TABLE public.course_plan_week_information ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_plan_week_information_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.course_topic (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    is_locked boolean NOT NULL,
    title character varying(255) NOT NULL,
    course_id bigint NOT NULL
);



ALTER TABLE public.course_topic ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.enrolled_course (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_paid boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);



ALTER TABLE public.enrolled_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrolled_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.notice (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    details character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);



ALTER TABLE public.notice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.notice_recipient (
    notice_id bigint NOT NULL,
    user_id bigint NOT NULL
);



CREATE TABLE public.payment (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_paid boolean NOT NULL,
    paid_amount real NOT NULL,
    paid_from character varying(255) NOT NULL,
    transaction_id character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    enrolled_course_id bigint NOT NULL
);



ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.quiz (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    duration integer NOT NULL,
    question_mark integer NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    video_id bigint NOT NULL
);



CREATE TABLE public.quiz_answer (
    id bigint NOT NULL,
    is_correct boolean NOT NULL,
    title character varying(255) NOT NULL,
    quiz_question_id bigint NOT NULL
);



ALTER TABLE public.quiz_answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE public.quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.quiz_question (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    quiz_id bigint NOT NULL
);



ALTER TABLE public.quiz_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.quiz_result (
    id bigint NOT NULL,
    quiz_id bigint NOT NULL,
    user_id bigint NOT NULL
);



ALTER TABLE public.quiz_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.result_answers (
    quiz_result_id bigint NOT NULL,
    is_correct boolean,
    question_id bigint NOT NULL
);



CREATE TABLE public.role (
    id bigint NOT NULL,
    name character varying(255),
    CONSTRAINT role_name_check CHECK (((name)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_TEACHER'::character varying, 'ROLE_STUDENT'::character varying])::text[])))
);



ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);



CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_school character varying(255),
    curriculum character varying(255) NOT NULL,
    date_of_birth date NOT NULL,
    email character varying(255) NOT NULL,
    father_name character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    grade character varying(255) NOT NULL,
    guardian_contact character varying(255) NOT NULL,
    guardian_email character varying(255) NOT NULL,
    last_seen_notice timestamp(6) without time zone,
    mother_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    uid character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_curriculum_check CHECK (((curriculum)::text = ANY ((ARRAY['CAMBRIDGE'::character varying, 'OXFORD'::character varying, 'PEARSON'::character varying, 'IB'::character varying])::text[]))),
    CONSTRAINT users_grade_check CHECK (((grade)::text = ANY ((ARRAY['VI'::character varying, 'VII'::character varying, 'VIII'::character varying, 'IX'::character varying, 'X'::character varying])::text[])))
);



ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.barchart_values
    ADD CONSTRAINT barchart_values_pkey PRIMARY KEY (course_information_id, topic_name);



ALTER TABLE ONLY public.contact_request
    ADD CONSTRAINT contact_request_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.course_bundle
    ADD CONSTRAINT course_bundle_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.course_file
    ADD CONSTRAINT course_file_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.course_information
    ADD CONSTRAINT course_information_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.course_plan_information
    ADD CONSTRAINT course_plan_information_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.course_plan_week_details_information
    ADD CONSTRAINT course_plan_week_details_information_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.course_plan_week_information
    ADD CONSTRAINT course_plan_week_information_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.course_topic
    ADD CONSTRAINT course_topic_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.enrolled_course
    ADD CONSTRAINT enrolled_course_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.notice
    ADD CONSTRAINT notice_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.quiz_answer
    ADD CONSTRAINT quiz_answer_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.quiz_question
    ADD CONSTRAINT quiz_question_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.quiz_result
    ADD CONSTRAINT quiz_result_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.result_answers
    ADD CONSTRAINT result_answers_pkey PRIMARY KEY (quiz_result_id, question_id);



ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.payment
    ADD CONSTRAINT ukgmhvhbh0gnwno1xhtd0ajwbfw UNIQUE (enrolled_course_id);



ALTER TABLE ONLY public.course_plan_information
    ADD CONSTRAINT ukl852iwyct7v7fbvsoe79169ku UNIQUE (course_information_id);



ALTER TABLE ONLY public.course_information
    ADD CONSTRAINT ukoc85m0ggbq6mive5yg0wylwfs UNIQUE (course_id);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.course_file
    ADD CONSTRAINT fk1kwwnhvd2dtl3cr7yx8j41x27 FOREIGN KEY (course_topic_id) REFERENCES public.course_topic(id);



ALTER TABLE ONLY public.quiz_answer
    ADD CONSTRAINT fk1tfpvs7phj0firv5btt04yrsd FOREIGN KEY (quiz_question_id) REFERENCES public.quiz_question(id);



ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fk4vnu0wnfy98u5ya012pvdfqx6 FOREIGN KEY (enrolled_course_id) REFERENCES public.enrolled_course(id);



ALTER TABLE ONLY public.course_topic
    ADD CONSTRAINT fk6esfb41t5ja5jp8p49uv72x9d FOREIGN KEY (course_id) REFERENCES public.course(id);



ALTER TABLE ONLY public.enrolled_course
    ADD CONSTRAINT fk7ymxj31qf504o3u6sxmrx8mw1 FOREIGN KEY (course_id) REFERENCES public.course(id);



ALTER TABLE ONLY public.course_plan_week_details_information
    ADD CONSTRAINT fk92fui99egbswv1im1cei08thb FOREIGN KEY (course_plan_week_information_id) REFERENCES public.course_plan_week_information(id);



ALTER TABLE ONLY public.quiz_result
    ADD CONSTRAINT fkd49de4d3rwgtndq0n51w1isbx FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);



ALTER TABLE ONLY public.quiz_question
    ADD CONSTRAINT fkdtynvfjgh6e7fd8l0wk37nrpc FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);



ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkg19bvgsvmwahfv4lkhosfbwti FOREIGN KEY (enrolled_course_id) REFERENCES public.enrolled_course(id);



ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.barchart_values
    ADD CONSTRAINT fkjq8fu72e2vpg9qlo1is6r8ab1 FOREIGN KEY (course_information_id) REFERENCES public.course_information(id);



ALTER TABLE ONLY public.enrolled_course
    ADD CONSTRAINT fkk8ixdkyfspv9915bclrv85b4j FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.course_plan_week_information
    ADD CONSTRAINT fkkfomnakje0r1sil3o57c0grva FOREIGN KEY (course_plan_information_id) REFERENCES public.course_plan_information(id);



ALTER TABLE ONLY public.course_bundle_course
    ADD CONSTRAINT fkmiu0oktucvagd8ko3hv0yqeua FOREIGN KEY (course_id) REFERENCES public.course(id);



ALTER TABLE ONLY public.notice_recipient
    ADD CONSTRAINT fkn7l7twsk5f0rmgme4b1ltycph FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.quiz_result
    ADD CONSTRAINT fknuben697e3lorbhgsbif22f2t FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.notice_recipient
    ADD CONSTRAINT fkqf9tm5y33egrwv60bg8jd8wfn FOREIGN KEY (notice_id) REFERENCES public.notice(id);



ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT fkrg57rqsiyf6nm7md0jpbnbdpq FOREIGN KEY (video_id) REFERENCES public.course_file(id);



ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id) REFERENCES public.role(id);



ALTER TABLE ONLY public.result_answers
    ADD CONSTRAINT fks7gqw5930osnd4vrc07ug92k1 FOREIGN KEY (quiz_result_id) REFERENCES public.quiz_result(id);



ALTER TABLE ONLY public.course_plan_information
    ADD CONSTRAINT fksnh4u56d0p3nnd70xibkxxru FOREIGN KEY (course_information_id) REFERENCES public.course_information(id);



ALTER TABLE ONLY public.course_information
    ADD CONSTRAINT fksy1fiq0mm5id77ww5811ni9xl FOREIGN KEY (course_id) REFERENCES public.course(id);



ALTER TABLE ONLY public.course_bundle_course
    ADD CONSTRAINT fkt389vqdvqq31wkaof8ghqmhu5 FOREIGN KEY (course_bundle_id) REFERENCES public.course_bundle(id);